export const styleTags: Record<string, string> = {
  tech: 'Tech',
  'dance-style': 'Dance',
  speed: 'Speed',
  balanced: 'Balanced',
  challenge: 'Challenge',
  accuracy: 'Accuracy',
  fitness: 'Fitness',
}

export const genreTags: Record<string, string> = {
  swing: 'Swing',
  nightcore: 'Nightcore',
  'folk-acoustic': 'Folk & Acoustic',
  'kids-family': 'Kids & Family',
  ambient: 'Ambient',
  'funk-disco': 'Funk & Disco',
  jazz: 'Jazz',
  'classical-orchestral': 'Classical & Orchestral',
  soul: 'Soul',
  speedcore: 'Speedcore',
  punk: 'Punk',
  rb: 'R&B',
  holiday: 'Holiday',
  vocaloid: 'Vocaloid',
  'j-rock': 'J-Rock',
  trance: 'Trance',
  'drum-and-bass': 'Drum and Bass',
  'comedy-meme': 'Comedy & Meme',
  instrumental: 'Instrumental',
  hardcore: 'Hardcore',
  'k-pop': 'K-Pop',
  indie: 'Indie',
  techno: 'Techno',
  house: 'House',
  'video-game-soundtrack': 'Video Game',
  'tv-movie-soundtrack': 'TV & Film',
  alternative: 'Alternative',
  dubstep: 'Dubstep',
  metal: 'Metal',
  anime: 'Anime',
  'hip-hop-rap': 'Hip Hop & Rap',
  'j-pop': 'J-Pop',
  dance: 'Dance',
  rock: 'Rock',
  pop: 'Pop',
  electronic: 'Electronic',
}

export const characteristics: Record<string, string> = {
  Standard: 'standard',
  OneSaber: 'one-saber',
  NoArrows: 'no-arrows',
  '90Degree': '90-degree',
  '360Degree': '360-degree',
  Lightshow: 'lightshow',
  Lawless: 'lawless',
  Legacy: 'legacy',
}

export const difficulties: Record<string, { shortName: string; slug: string }> = {
  Easy: { shortName: 'E', slug: 'easy' },
  Normal: { shortName: 'N', slug: 'normal' },
  Hard: { shortName: 'H', slug: 'hard' },
  Expert: { shortName: 'X', slug: 'expert' },
  ExpertPlus: { shortName: 'X+', slug: 'expert-plus' },
}

export const postCategories: Record<string, string> = {
  announcement: 'Announcement',
  news: 'News',
  guide: 'Guide',
  article: 'Article',
  interview: 'Interview',
  event: 'Event',
}
